#!/usr/bin/env bash

# ~/.macos — https://mths.be/macos

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

###############################################################################
# iTerm                                                                       #
###############################################################################
defaults write com.googlecode.iterm2 "PrefsCustomFolder" -string "~/dotfiles/iterm"
defaults write com.googlecode.iterm2 "LoadPrefsFromCustomFolder" -bool true

###############################################################################
# General UI/UX                                                               #
###############################################################################

# ========== Apprerance ==========
# - Light
# defaults delete .GlobalPreferences AppleInterfaceStyleSwitchesAutomatically > /dev/null 2>&1
# defaults delete .GlobalPreferences AppleInterfaceStyle > /dev/null 2>&1
# - Dark
defaults delete .GlobalPreferences AppleInterfaceStyleSwitchesAutomatically > /dev/null 2>&1
defaults write .GlobalPreferences AppleInterfaceStyle -string "Dark"
# - Auto
# defaults write .GlobalPreferences AppleInterfaceStyleSwitchesAutomatically -bool true

# ========== Show Battery status in menu bar ==========
# - Checked
defaults write com.apple.controlcenter "NSStatusItem Visible Battery" -bool true
defaults write ~/Library/Preferences/ByHost/com.apple.controlcenter.plist Battery -int 18
# - Unchecked
# defaults write com.apple.controlcenter "NSStatusItem Visible Battery" -bool false
# defaults write ~/Library/Preferences/ByHost/com.apple.controlcenter.plist Battery -int 24

# ========== Show Battery percentage in menu bar ==========
# - Show
defaults write ~/Library/Preferences/ByHost/com.apple.controlcenter.plist BatteryShowPercentage -bool true
# - Hide
# defaults write ~/Library/Preferences/ByHost/com.apple.controlcenter.plist BatteryShowPercentage -bool false

NPLIST="/private/var/root/Library/Preferences/com.apple.CoreBrightness.plist"

# ========== Turn keyboard backlight off after ~~~ of inactivity ==========
# @int:second
sudo /usr/libexec/PlistBuddy -c "Set :KeyboardBacklight:KeyboardBacklightIdleDimTime 0" ${NPLIST}

# ========== Use a 24-hour clock ==========
# - Checked
defaults write com.apple.menuextra.clock Show24Hour -bool true
# - Unchecked
# defaults write com.apple.menuextra.clock Show24Hour -bool false

# ========== Show date (In BigSur, time always appears) ==========
# - Checked
defaults write com.apple.menuextra.clock ShowDayOfMonth -bool true
# - Unchecked

# Disable smart quotes to save yourself from pesky syntax errors
# if the command doesn't work check:
# https://til.marcuse.info/macos/disable-smart-quotes-in-slack.html
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

# Disable automatic capitalization as it’s annoying when typing code
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

# Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Trackpad: enable tap to click for this user and for the login screen
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# Disable “natural” (Lion-style) scrolling
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

# The defaults for a freshly installed macOS Sierra 10.12.5 are:
# InitialKeyRepeat = 25 and KeyRepeat = 6
# The step values that correspond to the sliders on the GUI are as follow (lower equals faster):
# KeyRepeat: 120, 90, 60, 30, 12, 6, 2
# InitialKeyRepeat: 120, 94, 68, 35, 25, 15
#
# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1
# Set a shorter Delay until key repeat
defaults write NSGlobalDomain InitialKeyRepeat -int 12

# Create a shortcut to maximize the current window with Command + Shift + m
# Command: @
# Control: ^
# Option: ~
# Shift: $
# Tab: \U21e5 (Unicode code point for ⇥ character)
defaults write -globalDomain NSUserKeyEquivalents -dict-add "Zoom" "@\$m";

###############################################################################
# Finder                                                                      #
###############################################################################

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Use list view in all Finder windows by default
# Four-letter codes for the other view modes: `icnv`, `clmv`, `glyv`
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# ========== New Finder windows show ==========
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/Projects"

# ========== Open folders in tabs instead of new windows (only when you press command and click on a folder) ==========
# - Checked
defaults write com.apple.finder FinderSpawnTab -bool true
# - Unchecked
# defaults write com.apple.finder FinderSpawnTab -bool false

# ========== Show warning before changing an extension ==========
# - Checked
# defaults write com.apple.finder FXEnableExtensionChangeWarning -bool true
# - Unchecked
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# ========== Text Size ==========
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:textSize 14" "${HOME}"/Library/Preferences/com.apple.finder.plist

###############################################################################
# Dock, Dashboard, and hot corners                                            #
###############################################################################

# Set the icon size of Dock items to 64 pixels
defaults write com.apple.dock tilesize -int 64

###############################################################################
# Siri                                                                        #
###############################################################################

# ========== Enable Ask Siri ==========
# - Checked
# defaults write com.apple.assistant.support.plist Assistant Enabled -bool true
# - Unchecked
defaults write com.apple.assistant.support.plist "Assistant Enabled" -bool false

# ========== Show Siri in menu bar ==========
# - Checked
# defaults write com.apple.Siri StatusMenuVisible -bool true
# - Unchecked
defaults write com.apple.Siri StatusMenuVisible -bool false

echo "Please restart your macOS so all changes can take effect."
