# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

plugins=(
  git
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# load aliases
[[ -f ~/.aliases ]] && source ~/.aliases

[[ -f ~/.functions ]] && source ~/.functions

[[ -f ~/.private ]] && source ~/.private

# Set default locale for VIM
export LC_ALL=en_US.UTF-8

export EDITOR=vim
export BUNDLER_EDITOR=subl
# prevent update whenever you run a brew command
export HOMEBREW_NO_AUTO_UPDATE=1

# enable a command history feature for the iex console
# https://elixirforum.com/t/is-it-possible-to-enable-a-command-history-feature-for-the-iex-console/27409
export ERL_AFLAGS="-kernel shell_history enabled"

# from zsh-autosuggestions
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=10"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# enable file preview when searching files with fzf, need bat installed to have colored output
# set following binds while fzf is open:
#
# - ctrl+e: open selected file with sublime text
# - ctrl+y: copy selected file path
#
# inspiration: https://stackoverflow.com/questions/64753153/cant-preview-directory-using-fzf
#
export FZF_DEFAULT_OPTS='
  --bind "ctrl-y:execute-silent(echo {+} | pbcopy)"
  --bind "ctrl-e:execute(echo {+} | xargs -o subl)"
  --preview "([[ -f {} ]] && bat --style=numbers --color=always --line-range :500 {})"
'

echo "
  ALIASES
  f: search files with fzf (use ctrl+e to open selected file with sublime text)
"
