# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

eval "$(/opt/homebrew/bin/brew shellenv)"

ZSH_THEME="miloshadzic"

# add time to right side of terminal - can be replace by iTerm cmd+shift+e
# export RPROMPT="[%*]"

plugins=(
  git
  # fzf-tab
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# This will check for updates every x days
zstyle ':omz:update' frequency 60

# load aliases
[[ -f ~/.aliases ]] && source ~/.aliases

[[ -f ~/.functions ]] && source ~/.functions

[[ -f ~/.private ]] && source ~/.private

# Set default locale for VIM
export LC_ALL=en_US.UTF-8

# https://build.betterup.com/one-weird-trick-that-will-speed-up-your-bundle-install/
#export MAKE="make -j$(nproc)"
export BUNDLE_JOBS=$(nproc)

export DISABLE_SPRING=1

export EDITOR=vim
export BUNDLER_EDITOR=subl
# prevent update whenever you run a brew command
export HOMEBREW_NO_AUTO_UPDATE=1

# enable a command history feature for the iex console
# https://elixirforum.com/t/is-it-possible-to-enable-a-command-history-feature-for-the-iex-console/27409
export ERL_AFLAGS="-kernel shell_history enabled"

# from zsh-autosuggestions
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=10"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# enable file preview when searching files with fzf, need bat installed to have colored output
# set following binds while fzf is open:
#
# - ctrl+e: open selected file with sublime text
# - ctrl+y: copy selected file path
#
# inspiration: https://stackoverflow.com/questions/64753153/cant-preview-directory-using-fzf
#
export FZF_DEFAULT_OPTS='
  --bind "ctrl-y:execute-silent(echo {+} | pbcopy)"
  --bind "ctrl-e:execute(echo {+} | xargs -o subl)"
  --preview "([[ -f {} ]] && bat --theme=TwoDark --style=numbers --color=always --line-range :500 {})"
'

# disable preview when searching history (CTRL+R)
export FZF_CTRL_R_OPTS='--preview-window=:hidden'

# load zsh-autopair
source ~/.zsh-autopair/autopair.zsh
autopair-init

# trigger fzf when pressing arrow up
# bindkey "${key[Up]}" fzf-history-widget

# display weather (short version)
cli_short

BOLD='\033[1m'
NONE='\033[00m'
GREEN='\033[01;32m'

echo "
  ${GREEN}ALIASES${NONE}

  ${BOLD}rg:${NONE} search file content (ignore files on .gitignore)
  ${BOLD}b:${NONE} bundle install -j$(nproc)
  ${BOLD}br:${NONE} open bull run (ex: ${BOLD}br itub3${NONE})
  ${BOLD}cal:${NONE} calendar
  ${BOLD}cli:${NONE} weather
  ${BOLD}e:${NONE} editor
  ${BOLD}f:${NONE} search files with fzf (use ctrl+e to open selected file with sublime text)
  ${BOLD}ff:${NONE} switch to firefox
  ${BOLD}flushdns:${NONE} flush dns
  ${BOLD}gf:${NONE} open guru focus (ex: ${BOLD}gf meli${NONE})
  ${BOLD}yf:${NONE} open yahoo finance (ex: ${BOLD}yf baba${NONE})
  ${BOLD}gl:${NONE} open google on firefox
  ${BOLD}imgcat:${NONE} display image (ex: ${BOLD}imgcat foo.jpg${NONE})
  ${BOLD}using_port:${NONE} show processes using the given port. Ex: ${BOLD}using_port tcp:3000${NONE}
  ${BOLD}kill_all_in_port:${NONE} kill all processes using the given port. Ex: ${BOLD}kill_all_in_port tcp:3000${NONE}
  ${BOLD}killruby:${NONE} kill all ruby processes
  ${BOLD}pc:${NONE} pgcli
  ${BOLD}tw:${NONE} open twitter on brave
  ${BOLD}yt:${NONE} open youtube on brave
"

export PATH="$HOME/.poetry/bin:$PATH"

# NeoVim v0.7 binary must be present on this folder
# NeoVim installed from brew is v0.5 (outdated), Telescope plugin requires NeoVim min v0.7
# follow instructions from https://github.com/neovim/neovim/releases/tag/v0.7.2
# then add to the $PATH
export PATH="$HOME/nvim-macos/bin:$PATH"
export NEOVIM_CONFIG_FILE="~/.config/nvim/init.vim"
alias cfv="e $NEOVIM_CONFIG_FILE"

export PATH="$HOME/.local/bin/:$PATH"
