# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

plugins=(
  git
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# load aliases
[[ -f ~/.aliases ]] && source ~/.aliases

[[ -f ~/.functions ]] && source ~/.functions

[[ -f ~/.private ]] && source ~/.private

# Set default locale for VIM
export LC_ALL=en_US.UTF-8

export EDITOR=vim
export BUNDLER_EDITOR=subl

# from zsh-autosuggestions
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=10"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
