#!/bin/bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

echo "Installing oh-my-zsh"
RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

git clone https://github.com/hlissner/zsh-autopair ~/.zsh-autopair
git clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"
git clone https://github.com/Aloxaf/fzf-tab "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fzf-tab"

echo "Setting up macOS..."
source ~/.macos

echo "Installing Mise..."
curl https://mise.run | sh

echo "Setting up dotfiles..."
rm ~/.zshrc
cd ~/dotfiles && make update

echo "Installing brew packages..."
brew bundle --file=script/Brewfile

echo "Done :)"
