#!/bin/bash

echo "Installing Oh my ZSH..."
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
chsh -s /bin/zsh
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.oh-my-zsh/plugins/zsh-autosuggestions

# echo "Installing asdf..."
# git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.6.2
# asdf plugin-add erlang
# asdf plugin-add elixir

echo "Setup configuration files..."

config_files=~/dotfiles/config/*

for file in $config_files; do
  config=$(basename $file)
  echo "Creating symlink for .$config"
  ln -s $file ~/.$config
done

# echo "Setting iterm2 preferences folder..."
# defaults write com.googlecode.iterm2 "PrefsCustomFolder" -string "~/dotfiles/iterm"
# defaults write com.googlecode.iterm2 "LoadPrefsFromCustomFolder" -bool true

echo "Done :)"
